version: "3.7"

services:
  redis:
    image: "redis:latest"
    networks:
      - back
  crawler:
    build: ./crawler
    depends_on:
      - redis
      - controller
    networks:
      - back
  buyer:
    build: ./buyer
    depends_on:
      - redis
      - controller
      - crawler
    networks:
      - back
  controller:
    build: ./controller
    depends_on:
      - redis
    ports:
      - "80:80"
    networks:
      - back
networks:
  back:
    ipam:
      driver: default
      config:
        - subnet: "192.168.11.0/24"
