import Head from "next/head";
import Account from "../components/Account";
import Menu from "../components/Menu";
import List from "../components/List";
import Search from "../components/Search";
import { useState, useEffect } from "react";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import axios from "axios";

export default function Home() {
	const [currentMenu, setCurrentMenu] = useState("search");
	const [status, setStatus] = useState("online");

	useEffect(() => {
		setInterval(() => {
			axios.get("api/getStatus").then((res) => {
				console.log("getStatus", res.data);
				setStatus(res.data);
				if (res.data.needsPhoneAuth2) {
					let prompt = window.prompt("Enter phone auth code");
					axios.post(`http://${process.env.IP}/phoneAuth2`, {
						phoneAuth2: prompt,
					});
				}
			});
		}, 2000);
	}, []);

	return (
		<div className="">
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="flex min-h-screen">
				<Menu
					status={status}
					currentMenu={currentMenu}
					setCurrentMenu={setCurrentMenu}
				/>

				{currentMenu == "list" && (
					<List
						currentMenu={currentMenu}
						setCurrentMenu={setCurrentMenu}
					/>
				)}
				{currentMenu == "account" && (
					<Account
						currentMenu={currentMenu}
						setCurrentMenu={setCurrentMenu}
					/>
				)}
				{currentMenu == "search" && (
					<Search
						currentMenu={currentMenu}
						setCurrentMenu={setCurrentMenu}
					/>
				)}
			</div>
		</div>
	);
}
